### ISSUE TITLE
Problem with example for yt write_bitmap

### ISSUE THREAD

**Issue by esoPanda** [radio-astro-tools/spectral-cube#193] opened 2015-03-13 16:37 UTC
In this example:

http://spectral-cube.readthedocs.org/en/latest/yt_example.html#visualization-example

the final step, `write_bitmap(snapshot, 'cube_rendering.png', transpose=True)`, fails with this traceback:
```
In [72]: write_bitmap(snapshot, 'cube_rendering.png', transpose=True)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-72-d570ef0f1c1c> in <module>()
----> 1 write_bitmap(snapshot.value, 'cube_rendering.png', transpose=True)

/home/kwang/anaconda/lib/python2.7/site-packages/yt/visualization/image_writer.pyc in write_bitmap(bitmap_array, filename, max_val, transpose)
    165         bitmap_array = bitmap_array.swapaxes(0,1)
    166     if filename is not None:
--> 167         pw.write_png(bitmap_array, filename)
    168     else:
    169         return pw.write_png_to_string(bitmap_array.copy())

/home/kwang/anaconda/lib/python2.7/site-packages/yt/utilities/png_writer.pyc in write_png(buffer, filename, dpi)
     17     width = buffer.shape[1]
     18     height = buffer.shape[0]
---> 19     _png.write_png(buffer, width, height, filename, dpi)
     20 
     21 def write_png_to_string(buffer, dpi=100, gray=0):

TypeError: First argument must be an rgba buffer.
> /home/kwang/anaconda/lib/python2.7/site-packages/yt/utilities/png_writer.py(19)write_png()
     18     height = buffer.shape[0]
---> 19     _png.write_png(buffer, width, height, filename, dpi)
     20 

ipdb> 

```

@jzuhone can you comment on this?

**Comment by jzuhone** [comment] 2015-03-13 17:09
Hi @esoPanda, just a quick question first--what's the version of yt you are using?

**Comment by esoPanda** [comment] 2015-03-13 17:14
I'm using 3.0.2

**Comment by esoPanda** [comment] 2015-03-13 17:28
@jzuhone, I'm using yt 3.0.2

**Comment by jzuhone** [comment] 2015-03-13 17:33
Ok, I'll have a look at this later today and see if I can reproduce it.

**Comment by keflavich** [comment] 2015-03-13 17:34
@jzuhone when we inspected the data, `buffer` was a `[N,N,4]` Quantity (so it had a unit).  I tried using the `.value` to get a pure numpy dtype=float64 array and that did not solve the problem.

**Comment by jzuhone** [comment] 2015-03-13 17:36
@keflavich ok, that's odd, since it appears to be the correct shape at least. will investigate.

**Comment by jzuhone** [comment] 2015-07-16 02:32
Sorry for the delay on this one--this is a yt bug (though the example in the docs also needs updating). I will be fixing both tomorrow. Thanks for pointing this out, @esoPanda.

**Comment by jzuhone** [comment] 2015-07-19 00:50
This is fixed in the latest dev version of yt:

https://bitbucket.org/yt_analysis/yt/commits/f2357819d9dcbdcdb3cdd830c04dd7bb45a31290

Update the latest development version, or wait for the 3.2 stable version, which will be released in about a week or so.

**Comment by jzuhone** [comment] 2015-07-19 00:51
@keflavich I can't close the issue--can you?

**Closed** 2015-07-19 01:01 UTC

**Comment by lpsinger** [comment] 2015-12-28 21:30
I'm getting the same issue with yt 3.2.1.
